server:
  port: 38083
springdoc:
  packages-to-scan:
    - pers.ken.rt.data.controller
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    display-operation-id: true
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  config:
    activate:
      on-profile: dev
  application:
    name: rt-auth
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
logging:
  file:
    path: ./logs
