/*
 * This file was generated by the Gradle 'init' task.
 */
rootProject.name = "right-track-platform"
include(":rt-common")
include(":rt-gateway")
include(":rt-mall")
include(":rt-auth")
include("rt-map")
include(":pbac-spring-boot-starter")
include(":storage-spring-boot-starter")
project(":pbac-spring-boot-starter").projectDir = file("rt-common-starter/pbac-spring-boot-starter")
project(":storage-spring-boot-starter").projectDir = file("rt-common-starter/storage-spring-boot-starter")
pluginManagement {
    repositories {
        maven("https://maven.aliyun.com/repository/gradle-plugin")
    }
}

// 启用 catalog（settings.gradle.kts）
@Suppress("UnstableApiUsage")
dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
        }
    }
}
