server:
  port: 38080
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  config:
    activate:
      on-profile: dev
  application:
    name: rt-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:38081/oauth2/jwks
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        file-extension: yaml
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: mall-service
          uri: lb://rt-mall
          predicates:
            - Path=/mall/**
          filters:
            - RewritePath=/mall/(?<path>.*), /$\{path}
        - id: test-service
          uri: lb://test
          predicates:
            - Path=/test/**
          filters:
            - RewritePath=/test/(?<path>.*), /$\{path}
        - id: openapi
          uri: lb://gateway-service
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs


oauth:
  white-list-urls:
    - /uc/rsa/getPublicKey
    - /uc/oauth/**
    - /swagger-ui/**
    - /swagger-resources/**
    - /webjars/**
    - /v3/api-docs/**
    - /v2/api-docs/**
logging:
  file:
    path: ./logs
#oauth2:
#  client:
#    client-id: ${spring.application.name}
#    client-secret: 123456
#    user-authorization-uri: http://localhost:38081/oauth/authorize
#    access-token-uri: http://localhost:38081/oauth/token
#  resource:
#    id: ${spring.application.name}
#    user-info-uri: user-info
#  authorization:
#    check-token-access: http://localhost:38081/oauth/check_token

