server:
  port: 38080
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  config:
    activate:
      on-profile: dev
  application:
    name: rt-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: http://172.18.17.81:38081
          jwk-set-uri: http://localhost:38081/oauth2/jwks
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        file-extension: yaml
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: mall-service
          uri: lb://rt-mall
          predicates:
            - Path=/mall/api/**
          filters:
            - RewritePath=/mall/api/(?<path>.*), /$\{path}
        - id: auth-service
          uri: lb://rt-auth
          predicates:
            - Path=/auth/api/**
          filters:
            - RewritePath=/auth/api/(?<path>.*), /$\{path}
        - id: test-service
          uri: lb://test
          predicates:
            - Path=/test/api/**
          filters:
            - RewritePath=/test/api/(?<path>.*), /$\{path}
        - id: openapi
          uri: lb://gateway-service
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
auth:
  resource-server:
    white-list:
      - /*/webjars/**
      - /*/v3/api-docs/**
      - /*/swagger-ui/**
      - /*/swagger-resources/**
      - /*/css/**
      - /*/js/**
      - /*/images/**
      - /favicon.ico
      - /swagger-ui.html


logging:
  file:
    path: ./logs

springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    display-operation-id: true
