server:
  port: 38080
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: gateway-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        file-extension: yaml
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: uaa-service
          uri: lb://uaa
          predicates:
            - Path=/uaa/**
          filters:
            - RewritePath=/uaa/(?<path>.*), /$\{path}
        - id: iam-service
          uri: lb://iam
          predicates:
            - Path=/iam/**
          filters:
            - RewritePath=/iam/(?<path>.*), /$\{path}
        - id: test-service
          uri: lb://test
          predicates:
            - Path=/test/**
          filters:
            - RewritePath=/test/(?<path>.*), /$\{path}
        - id: openapi
          uri: lb://gateway-service
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

oauth:
  white-list-urls:
    - /uc/rsa/getPublicKey
    - /uc/oauth/**
    - /swagger-ui/**
    - /swagger-resources/**
    - /webjars/**
    - /v3/api-docs/**
    - /v2/api-docs/**
logging:
  file:
    path: logs/
#oauth2:
#  client:
#    client-id: ${spring.application.name}
#    client-secret: 123456
#    user-authorization-uri: http://localhost:38081/oauth/authorize
#    access-token-uri: http://localhost:38081/oauth/token
#  resource:
#    id: ${spring.application.name}
#    user-info-uri: user-info
#  authorization:
#    check-token-access: http://localhost:38081/oauth/check_token

