/*
 * This file was generated by the Gradle 'init' task.
 */



dependencies {
    implementation(project(":rt-common"))
    implementation(project(":rt-auth-api"))
    implementation(project(":rt-pbac-spring-boot-starter"))
    implementation(libs.mapstruct)
    annotationProcessor(libs.mapstruct.processor)
    implementation(libs.postgresql)
    implementation("com.baomidou:mybatis-plus-boot-starter:3.5.3.1")
    implementation(libs.springboot.security)
    implementation(libs.springboot.oauth2.resourceserver)
    implementation(libs.spring.security.authorizationserver)
    implementation(libs.springcloud.bootstrap)
    implementation(libs.alibaba.springcloud.nacos.discovery)
    implementation(libs.alibaba.springcloud.nacos.config)
    implementation(libs.springboot.configuration.processor)
    implementation(libs.springcloud.loadbalancer)
    testImplementation(libs.springboot.test)
}

description = "rt-auth-service"
