/*
 * This file was generated by the Gradle 'init' task.
 */
group = "pers.ken.rt"
description = "pbac-spring-boot-starter"


dependencies {
    api(project(":rt-common"))
    compileOnly("org.springframework.boot:spring-boot-starter-web")
    compileOnly("org.springframework.boot:spring-boot-starter-data-redis")
    compileOnly("org.springframework.boot:spring-boot-starter-aop")
    compileOnly("com.alibaba:druid:1.2.15")
    annotationProcessor("org.springframework.boot:spring-boot-configuration-processor")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("org.junit.jupiter:junit-jupiter-api")
    testImplementation("org.junit.jupiter:junit-jupiter-engine")
}



tasks.getByName<Test>("test") {
    useJUnitPlatform()
}