/*
 * This file was generated by the Gradle 'init' task.
 */
group = "pers.ken.rt"
description = "pbac-spring-boot-starter"
version = "1.0.0-SNAPSHOT"

plugins {
    java
    `maven-publish`
}

dependencies {
    implementation(libs.apache.common.lang3)
    implementation(libs.google.guava)
    implementation(libs.alibaba.druid)
    implementation("org.springframework.boot:spring-boot-starter")
    implementation("org.springframework.boot:spring-boot-autoconfigure")
    compileOnly("org.springframework.boot:spring-boot-starter-web")
    compileOnly("org.springframework.boot:spring-boot-starter-data-redis")
    compileOnly("org.springframework.boot:spring-boot-starter-aop")
    annotationProcessor("org.springframework.boot:spring-boot-configuration-processor")

    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("org.junit.jupiter:junit-jupiter-api")
    testImplementation("org.junit.jupiter:junit-jupiter-engine")
}

tasks.getByName<Test>("test") {
    useJUnitPlatform()
}

publishing {
    publications {
        register<MavenPublication>("mavenJava") {
            from(components["java"])
        }
    }
}
