/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    id("java")
    `version-catalog`
    kotlin("jvm") version ("1.9.23")
}

description = "rt-auth"

dependencies {
    // project
    implementation(project(":rt-common"))
    implementation(libs.pbac.spring.boot.starter)
    // spring family
    implementation(libs.spring.session.redis)
    implementation(libs.springboot.data.redis)
    implementation(libs.springboot.aop)
    implementation(libs.springboot.security)
    implementation(libs.springboot.oauth2.client)
    implementation(libs.spring.security.authorizationserver)
    implementation(libs.springboot.autoconfigure)
    annotationProcessor(libs.springboot.configuration.processor)
    // spring document
    implementation(libs.springdoc.openapi)
    // utils
    implementation(libs.mapstruct)
    annotationProcessor(libs.mapstruct.processor)
    // database
    implementation(libs.postgresql)
    implementation(libs.mybatis.starter)
    // test
    testImplementation(libs.springboot.test)

    tasks.bootJar {
        // 排除所有yml文件
        exclude("**/*.yml", "**/*.yaml")
        // Clean jar to prevent more than one jar
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        doLast {
            copy {
                from("${project.rootDir}/bin") { include("*.sh") }
                into("${project.buildDir}/libs")
            }
        }
    }
}


