/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java")
    `version-catalog`
    kotlin("jvm") version ("1.7.10")
}

description = "rt-auth"

dependencies {
    // project
    implementation(project(":rt-common"))
    implementation(project(":pbac-spring-boot-starter"))
    // spring family
    implementation(libs.spring.session.redis)
    implementation(libs.springboot.aop)
    implementation(libs.spring.security.authorizationserver)
    // 引入client是因为集成第三方平台做联合登录，认证服务就变成了Client端了
    implementation(libs.springboot.oauth2.client)
    implementation(libs.springboot.configuration.processor)
    // spring document
    implementation(libs.springdoc.openapi)
    // utils
    implementation(libs.mapstruct)
    annotationProcessor(libs.mapstruct.processor)
    // database
    implementation(libs.postgresql)
    implementation(libs.mybatis.starter)


    // test
    testImplementation(libs.springboot.test)
}


