import org.springframework.boot.gradle.tasks.bundling.BootJar

/*
 * This file was generated by the Gradle 'init' task.
 */
description = "rt-common"

plugins {
    java
    id("org.springframework.boot") version "3.3.5"
    id("io.spring.dependency-management") version "1.1.6"
    `version-catalog`
    kotlin("jvm") version ("1.7.10")
}

dependencies {
    // springboot
    api(libs.springboot.web)
    api(libs.springboot.validation)
    runtimeOnly(libs.springboot.devtools)

    // web
    api(libs.springdoc.openapi)
    api(libs.mapstruct)
    annotationProcessor(libs.mapstruct.processor)

    // utils
    api(libs.alibaba.druid)
    api(libs.google.guava)
    api(libs.jnanoid)
    api(libs.apache.common.lang3)
}


tasks.withType<Jar> {
    enabled = true
}

tasks.withType<BootJar> {
    enabled = false
}

