/*
 * This file was generated by the Gradle 'init' task.
 */

description = "rt-mall-service"

dependencies {
    implementation(project(":rt-common"))
    implementation(project(":rt-pbac-spring-boot-starter"))
    implementation(libs.postgresql)
    implementation(libs.springboot.data.jpa)
    implementation(libs.alibaba.springcloud.nacos.discovery)
    implementation(libs.alibaba.springcloud.nacos.config)
    implementation(libs.springboot.configuration.processor)
    implementation(libs.springcloud.bootstrap)
    testImplementation(libs.springboot.test)
}

