/*
 * This file was generated by the Gradle 'init' task.
 */

description = "rt-mall-service"

dependencies {
    api(project(":rt-common"))
    api(project(":rt-pbac-spring-boot-starter"))
    api(libs.postgresql)
    api(libs.hibernate.types55)
    api(libs.springboot.data.jpa)
    api(libs.alibaba.springcloud.nacos.discovery)
    api(libs.alibaba.springcloud.nacos.config)
    api(libs.springboot.configuration.processor)
    testImplementation(libs.springboot.test)
}

