/*
 * This file was generated by the Gradle 'init' task.
 */
description = "rt-gateway"
dependencies {
    // project
    implementation(project(":rt-common"))

    // springboot
    implementation(libs.springcloud.gateway)
    implementation(libs.springboot.security)
    implementation(libs.springboot.oauth2.resourceserver)
    implementation(libs.springboot.oauth2.client)
    implementation(libs.springboot.webflux)
    implementation(libs.springboot.actuator)
    annotationProcessor(libs.springboot.configuration.processor)

    // springcloud
    implementation(libs.springcloud.bootstrap)
    implementation(libs.springcloud.alibaba.sentinel.gateway)
    implementation(libs.springcloud.alibaba.sentinel)
    implementation(libs.springcloud.alibaba.nacos.discovery)
    implementation(libs.springcloud.alibaba.nacos.config)
    implementation(libs.springcloud.loadbalancer)

    // springDoc
    implementation(libs.springdoc.openapi.webflux)

}


