
### Oauth2.0 client_credentials
POST {{host}}/auth/api/oauth2/token?grant_type=client_credentials
Content-Type: application/x-www-form-urlencoded
Authorization: Basic bWVzc2FnaW5nLWNsaWVudDpzZWNyZXQ=

> {%
    client.global.set("auth_token", response.body.access_token);
%}

### Oauth2.0 Authoize
# localhost:38081/oauth2/authorize?response_type=code&client_id=messaging-client&scope=message.read&redirect_uri=http://127.0.0.1:38081/authorized
GET {{auth_host}}/oauth2/authorize?response_type=code&client_id=messaging-client&scope=message.read&
    redirect_uri=http://127.0.0.1:38081/authorized


### Oauth2.0 authorization_code
POST {{auth_host}}/oauth2/token?grant_type=authorization_code&redirect_uri=http://127.0.0.1:38081/authorized&
    code=e4B_WM1Fo0q3PX7yxSpMC_KxvsT3BZw2TivCTS73Hu1C56SdQO2gMleqtT4srLHIR4iUukKvQa8yx5RdKVSnXN1aaC8fMiCpy64bJ2VdekfmVJ1JB5J0_d7Jlwd6kq5f
Content-Type: application/x-www-form-urlencoded
Authorization: Basic bWVzc2FnaW5nLWNsaWVudDpzZWNyZXQ=

> {%
    client.log('access_token:' + response.body.access_token)
    client.global.set("access_token", response.body.access_token);
%}

### RefreshToken
POST {{host}}/auth/api/oauth2/token?grant_type=refresh_token&
    refresh_token=NCTbCPdzfwqVLTPIojQAZYW1jjfS2cYJKOW3ZxPdPTMCuH4wMOIl0rwEP5uPogQssmnSbLrNMtZBgsAvR1ZkKAZxSNIwxfiI3W2kDdjc9dxG1nM4QmWzRPb4fmjz6dvh
Content-Type: application/x-www-form-urlencoded


### Oauth2.0 jwks(获取公钥)
GET {{host}}/auth/api/oauth2/jwks
Content-Type: application/json

### Auth 获取用户策略
GET {{host}}/auth/api/users/1/policies
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

### Auth 获取当前用户策略
GET {{host}}/auth/api/v1/policies
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}


### 获取用户策略
GET {{auth_host}}/v1/policies
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}


