### Oauth2.0 client_credentials
POST http://localhost:38081/oauth2/token?grant_type=client_credentials
Content-Type: application/x-www-form-urlencoded
Authorization: Basic bWVzc2FnaW5nLWNsaWVudDpzZWNyZXQ=

> {%
    client.global.set("auth_token", response.body.access_token);
%}

### Oauth2.0 authorization_code
POST http://localhost:38081/oauth2/token?grant_type=authorization_code&redirect_uri=http://127.0.0.1:38081/authorized&
    code=u2D4qoP1F3XIbvM2ziGeAlmqY1XDp4EWrtUufTXXIk0WdII72vVMpeVp3ow7DxXC5yYK5OLGL0qd4a-ATT_lF1vLf4AZjr6HGRZdlMn9FRhj5C98BAUNWdS-HuFKtp3q
Content-Type: application/x-www-form-urlencoded
Authorization: Basic bWVzc2FnaW5nLWNsaWVudDpzZWNyZXQ=

> {%
    client.global.set("auth_token", response.body.access_token);
%}

### Oauth2.0 jwks(获取公钥)
GET http://localhost:38081/oauth2/jwks
Content-Type: application/json

### Oauth2.0 authoize
GET http://127.0.0.1:38081/oauth2/authorize?response_type=code&client_id=messaging-client&scope=message.read&redirect_uri=http://127.0.0.1:38081/authorized


### Oauth2.0 资源服务器测试API
GET http://localhost:38080/test
Content-Type: application/json
Authorization: Bearer a19278bc-1f87-4a8a-bcc2-7ae52e5bef03


### Oauth2.0 资源服务器测试API2
GET http://localhost:38080/mall/test
Content-Type: application/json
Authorization: Bearer a19278bc-1f87-4a8a-bcc2-7ae52e5bef03

### Auth 获取用户策略
GET http://127.0.0.1:38081/users/1/policies
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}