### Oauth2.0 client_credentials
POST http://localhost:38081/oauth2/token?grant_type=client_credentials
Content-Type: application/x-www-form-urlencoded
Authorization: Basic bWVzc2FnaW5nLWNsaWVudDpzZWNyZXQ=

> {%
    client.global.set("auth_token", response.body.access_token);
%}

### Oauth2.0 authorization_code
POST http://localhost:38081/oauth2/token?grant_type=authorization_code&redirect_uri=http://127.0.0.1:38081/authorized&
    code=3_aUC7fBO_XfW1y-bOfs1pDf6QFEE96ToKNlYApFuTLtptDXZtvam7ss9KRFXuQyINi6qyCrQcZeyMMui7zWu3K2GFVKA6LXISOdExgiIlX3HZcSS_F2CVSwVcOwEv-B
Content-Type: application/x-www-form-urlencoded
Authorization: Basic bWVzc2FnaW5nLWNsaWVudDpzZWNyZXQ=

> {%
    client.global.set("auth_token", response.body.access_token);
%}

### Oauth2.0 jwks(获取公钥)
GET http://localhost:38081/oauth2/jwks
Content-Type: application/json

### Oauth2.0 资源服务器测试API
GET http://localhost:38080/test
Content-Type: application/json
Authorization: Bearer 03aff536-b9cd-4139-97b3-3e2b3ed3bf1c

### Oauth2.0 authoize
GET http://127.0.0.1:38081/oauth2/authorize?response_type=code&client_id=messaging-client&scope=message.read&redirect_uri=http://127.0.0.1:38081/authorized