### Oauth2.0 client_credentials
POST http://localhost:38081/oauth2/token?grant_type=client_credentials
Content-Type: application/x-www-form-urlencoded
Authorization: Basic bWVzc2FnaW5nLWNsaWVudDpzZWNyZXQ=

> {%
    client.global.set("auth_token", response.body.access_token);
%}

### Oauth2.0 SingleResourceTest
GET {{mall_host}}/categories/1001
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Oauth2.0 MultiResourceTest
GET {{mall_host}}/element1/400111/element2/123456
Content-Type: application/json
Authorization: Bearer {{auth_token}}