/*
 * This file was generated by the Gradle 'init' task.
 */
description = "rt-mall"

dependencies {
    implementation(project(":rt-common"))
    implementation(project(":pbac-spring-boot-starter"))
    implementation(libs.postgresql)
    implementation(libs.mybatis.starter)
    implementation(libs.springboot.data.jpa)
    implementation(libs.springcloud.alibaba.nacos.discovery)
    implementation(libs.springcloud.alibaba.nacos.config)
    implementation(libs.springboot.configuration.processor)
    implementation(libs.springcloud.bootstrap)
    testImplementation(libs.springboot.test)
}

