/*
 * This file was generated by the Gradle 'init' task.
 */

description = "rt-mall"

dependencies {
    implementation(project(":rt-common"))
    implementation(project(":pbac-spring-boot-starter"))
    implementation(libs.postgresql)
    implementation("com.baomidou:mybatis-plus-boot-starter:3.5.3.1")
    implementation(libs.springboot.data.jpa)
    implementation(libs.alibaba.springcloud.nacos.discovery)
    implementation(libs.alibaba.springcloud.nacos.config)
    implementation(libs.springboot.configuration.processor)
    implementation(libs.springcloud.bootstrap)
    testImplementation(libs.springboot.test)
}

