/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    id("java")
    `version-catalog`
    kotlin("jvm") version ("1.7.10")
}

description = "rt-mall"

dependencies {
    implementation(project(":rt-common"))
    implementation(project(":pbac-spring-boot-starter"))
    implementation(libs.postgresql)
    implementation(libs.mybatis.starter)
    implementation(libs.springboot.data.jpa)
    implementation(libs.alibaba.springcloud.nacos.discovery)
    implementation(libs.alibaba.springcloud.nacos.config)
    implementation(libs.springboot.configuration.processor)
    implementation(libs.springcloud.bootstrap)
    testImplementation(libs.springboot.test)
}

