/*
 * This file was generated by the Gradle 'init' task.
 */



dependencies {
    api(project(":rt-common"))
    compileOnly("org.springframework.boot:spring-boot-starter-web")
    compileOnly("org.springframework.boot:spring-boot-starter-data-redis")
    compileOnly("org.springframework.boot:spring-boot-starter-aop")
    compileOnly("com.alibaba:druid:1.2.15")
    annotationProcessor("org.springframework.boot:spring-boot-configuration-processor")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
}

group = "pers.ken.rt"
description = "rt-pbac-spring-boot-starter"

tasks.getByName<Test>("test") {
    useJUnitPlatform()
}